### ISSUE TITLE
gitlab配置时使用http地址报错

### ISSUE THREAD

**Issue by sampsonye** [go-atomci/atomci#10]
* `应用版本`:
     * `atomci-frontend`:  1.3.0
     * `atomci`: 1.3.0
* `Kubernetes`: 1.21
如图，配置的gitlab地址是http的，为何报错信息中显示的是https的地址呢？我并没有配置https
![image](https://user-images.githubusercontent.com/5895634/146031184-6d6a7dc1-d237-42b1-bc04-3b29037525b3.png)
```
scmclient get repositories list error: Get "https://180.76.53.109/api/v4/projects?membership=true&page=1&per_page=100": dial tcp 180.76.53.109:443: connect: connection refused
```

**Comment by sampsonye** [comment]
这里强制使用https是不是不合适？
![image](https://user-images.githubusercontent.com/5895634/146042010-ef0180be-822f-4702-b955-3d31c10db24d.png)

**Comment by colynn** [comment]
好的，可以提merge， 依赖于客户端的输入
