### ISSUE TITLE
从历史版本升级（1.4.0）通过变更镜像升级时，migrate 无法被正常触发

### ISSUE THREAD

**Issue by colynn** [go-atomci/atomci#115]
### 运行环境
* `应用版本`:
     * `atomci-frontend`: v1.5.0-feat-app-refactor
     * `atomci`: v1.5.0-feat-app-refactor
* `Kubernetes`: none

### 问题描述
从历史版本升级上来时，migrate 无法被正常触发， 但是 `last_migration_date` 会被更新为最新的migrate 文件。

### 截图
<img width="354" alt="image" src="https://user-images.githubusercontent.com/5203608/163989445-c2a4f52c-958e-4422-b6bc-a58eecf280a6.png">

### 如果复现
1. 先安装后 `1.4.0`的release 包
2. 然后通过变更`docker-compose.yml`的镜像至`1.5.0`,
       *  `colynn/atomci:1.5.0`
       * `colynn/atomci-frontend:1.5.0`
3. 重启服务
```sh
$ docker-compose stop atomci frontend
$ docker-compose up -d atomci frontend
```
4. 查看数据表即可看到如截图数据

**Comment by colynn** [comment]
如果没有执行过migrate, 是不是我们默认执行所有的migrate，如果能获取到last_migration_date  就使用这个时间？

**Comment by colynn** [comment]
@sampsonye 还有一个小问题，`last_migration_date`已经为最新migrate文件对应的日期了，如下图
<img width="293" alt="image" src="https://user-images.githubusercontent.com/5203608/164185522-fa0e3156-e5c4-4387-9aa6-b7d243a27f1c.png">


但是重启服务后，该日期的migrate还是会被触发。
<img width="680" alt="image" src="https://user-images.githubusercontent.com/5203608/164185823-41043237-61e6-4a2a-9502-894fa9cc7cb2.png">

**Comment by sampsonye** [comment]
> @sampsonye 还有一个小问题，`last_migration_date`已经为最新migrate文件对应的日期了，如下图 <img alt="image" width="293" src="https://user-images.githubusercontent.com/5203608/164185522-fa0e3156-e5c4-4387-9aa6-b7d243a27f1c.png">
> 
> 但是重启服务后，该日期的migrate还是会被触发。 <img alt="image" width="680" src="https://user-images.githubusercontent.com/5203608/164185823-41043237-61e6-4a2a-9502-894fa9cc7cb2.png">

看起来又是时区的问题，我再研究一下

**Comment by colynn** [comment]
@sampsonye 已确认，在已新安装的环境中 `migration20220414.go`未能正常执行导致的，已经兼容修复,  确认这个PR #119
