### ISSUE TITLE
构建部署查看详细日志白屏

### ISSUE THREAD

**Issue by sampsonye** [go-atomci/atomci#12]
### 运行环境
* `应用版本`:
     * `atomci-frontend`: 1.3.0
     * `atomci`:1.3.0
* `Kubernetes`:1.21.0

### 问题描述
查看构建部署的日志白屏
### 截图
![image](https://user-images.githubusercontent.com/5895634/146224580-dbcef62e-8f6d-4867-977f-5cce2d0a2b4d.png)

经分析，应该是js语法错误导致无法显示
![image](https://user-images.githubusercontent.com/5895634/146224725-96b6ac0b-c05c-4544-8294-cb33addde992.png)

**Comment by colynn** [comment]
thanks @sampsonye  fixed
