### ISSUE TITLE
v1.5.1 的harbor 作为镜像仓库无法集成配置

### ISSUE THREAD

**Issue by colynn** [go-atomci/atomci#136]
### 运行环境
* `应用版本`:
     * `atomci-frontend`: 1.5.0
     * `atomci`: 1.5.0
* `Kubernetes`: 1.22.0

### 问题描述
如下图

### 截图
![image](https://user-images.githubusercontent.com/5203608/167986163-d8b97c5a-3b3d-4e50-bb0a-7c6d2b1f46c6.png)

**Comment by colynn** [comment]
@sampsonye [registryhub.go#L20 这里](https://github.com/go-atomci/atomci/blob/master/internal/core/settings/registryhub.go#L20)  期望可以把具体的 err信息也返回出来

**Comment by sampsonye** [comment]
atomci支持1.5.1版本作为registry，本issus后续我将优化文案提示
![e87e4ffcd577d4717a68e5cb9a0601f](https://user-images.githubusercontent.com/5895634/168411469-605e8bb5-837d-4a0e-9ff5-606c65af5816.png)

![3eb2390b088f2fddf68a6beda494ece](https://user-images.githubusercontent.com/5895634/168411476-9bb36d7c-a1e9-4b64-a7e4-a2c173884dd7.png)
