### ISSUE TITLE
[Approve]添加关联仓库时，输入的是完整的仓库地址，而不是gitlab的host时，jenkins端拉取代码会失败

### ISSUE THREAD

**Issue by sampsonye** [go-atomci/atomci#14]
**您有什么需求，是否与某个功能或问题相关? 请描述**
添加关联仓库时，输入的是完整的仓库地址，而不是gitlab的host时，jenkins端拉取代码会失败

**你想要的解决方案是什么**
考虑友好提示用户确认输入的是gitlab服务端baseURL  或者服务端自行裁剪（需要明确知道baseURL才行，注意二级目录的影响）

**Comment by colynn** [comment]
vote + 1
