### ISSUE TITLE
构建时默认分支显示不正确

### ISSUE THREAD

**Issue by sampsonye** [go-atomci/atomci#149]
### 运行环境
* `应用版本`:
     * `atomci-frontend`: 
     * `atomci`:
* `Kubernetes`:

### 问题描述
开源仓库[BootstrapBlazor](https://gitee.com/LongbowEnterprise/BootstrapBlazor.git)默认主分支是main
atomci在构建时，显示默认分支是master（见截图），每次都必须手动更改，体验不好
### 截图
![image](https://user-images.githubusercontent.com/5895634/169283911-ff9af23a-8b72-417d-b1bb-3fe4ad948e6f.png)

**Comment by colynn** [comment]
默认显示哪个分支取决于 创建流水线的定义，如果创建流水线时默认选择`main`， 则默认就会是`main`分支， 如下图说明
<img width="940" alt="image" src="https://user-images.githubusercontent.com/5203608/169352968-fc713177-92f4-48bb-b6e8-00a288f9a94c.png">


<img width="1043" alt="image" src="https://user-images.githubusercontent.com/5203608/169352900-2bfb1cb8-985e-46ea-97b0-bb25cfeb7390.png">

**Comment by colynn** [comment]
#152

**Comment by sampsonye** [comment]
> 默认显示哪个分支取决于 创建流水线的定义，如果创建流水线时默认选择`main`， 则默认就会是`main`分支， 如下图说明 <img alt="image" width="940" src="https://user-images.githubusercontent.com/5203608/169352968-fc713177-92f4-48bb-b6e8-00a288f9a94c.png">
> 
> <img alt="image" width="1043" src="https://user-images.githubusercontent.com/5203608/169352900-2bfb1cb8-985e-46ea-97b0-bb25cfeb7390.png">

创建流水线时，分支为非必选项；此时“默认分支”的显示会出现问题

**Comment by colynn** [comment]
> > 默认显示哪个分支取决于 创建流水线的定义，如果创建流水线时默认选择`main`， 则默认就会是`main`分支， 如下图说明 <img alt="image" width="940" src="https://user-images.githubusercontent.com/5203608/169352968-fc713177-92f4-48bb-b6e8-00a288f9a94c.png">
> > <img alt="image" width="1043" src="https://user-images.githubusercontent.com/5203608/169352900-2bfb1cb8-985e-46ea-97b0-bb25cfeb7390.png">
> 
> 创建流水线时，分支为非必选项；此时“默认分支”的显示会出现问题

创建流水线时，分支的选择是必选项，有后端校验

**Comment by colynn** [comment]
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/5203608/169935777-9682eba7-03a2-4224-9b24-6b1a747600a0.png">
