### ISSUE TITLE
镜像版本规则设置为“系统默认规则”时不会构建镜像

### ISSUE THREAD

**Issue by sampsonye** [go-atomci/atomci#152]
### 运行环境
* `应用版本`:
     * `atomci-frontend`: 
     * `atomci`:
* `Kubernetes`:

### 问题描述
1. 应用编排时，配置镜像版本规则为“系统默认规则”
2. 构建时不会触发镜像构建
```
stage('Images') {
    steps {
        sh "echo 'there was no images items'"
    }
}
```
### 截图
![image](https://user-images.githubusercontent.com/5895634/169287209-f9a0852b-5d44-4c44-a05f-5d9430cb0d9c.png)

![image](https://user-images.githubusercontent.com/5895634/169287596-2f6ebd6e-d1f4-48b0-aa9f-ef17560bde63.png)

**Comment by colynn** [comment]
#149


因为使用“系统默认规则”时会根据创建的流水线关联的app分支获取commit信息，但是当前流水线创建时绑定的分支为无效的分支

所以无法获取到具体的commit，从而没有生成 images信息，


### 解决方案： 
方案1. 创建流水线时校验分支的有效性， 另外触发构建时禁止分支的切换
![image](https://user-images.githubusercontent.com/5203608/169631202-ebee1065-d233-4968-82bf-c08c8fef91cf.png)

![image](https://user-images.githubusercontent.com/5203608/169631190-1261cdb1-adf7-4705-b3c6-8d9dd82e19e1.png)


方案2. 类似1.1 添加分支有效性的校验，保留分支的切换， 生成镜像的信息不依赖流水线的app信息，而依赖于每一次触发流水线的上下文
![image](https://user-images.githubusercontent.com/5203608/169631361-9c4cf741-2f88-42d6-b909-cebc05ecbfdf.png)
![image](https://user-images.githubusercontent.com/5203608/169631378-e386b8af-bf34-4058-94b9-4d02a40ed17a.png)
