### ISSUE TITLE
项目编译环境配置

### ISSUE THREAD

**Issue by stainzhu** [go-atomci/atomci#154]
**您有什么需求，是否与某个功能或问题相关? 请描述**
![11391da41e151259f3a7417362b389b](https://user-images.githubusercontent.com/98097468/169476452-e501c374-e1dd-496a-8667-dff9e715e892.png)

![90d10c32fac6e14d58c21b35dcd7c54](https://user-images.githubusercontent.com/98097468/169476473-1a6e79e2-949a-4437-bec7-516e0fd5c4c5.png)

![a945b623600522f9be4d99f895e0af8](https://user-images.githubusercontent.com/98097468/169476537-216b1dd3-e80d-44e5-bf7c-c2e3b8248af3.png)

**你想要的解决方案是什么**

、此处需要验证环境名称是否重复的问题，如果有多个同名的编译环境，配置项目编译环境的时候无法选择

#
* 请你通过留下👍 表情为此issue投票，帮助社区和维护者优先考虑这个请求；
* 请不要留下 "+1 "或 "me too"的评论，它们会给问题订阅者带来额外的噪音，并且无助于优先处理请求。
* 如果你有兴趣在这个问题上工作，或者已经提交了pull request，请留下评论.

* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Comment by stainzhu** [comment]
此处需要验证环境名称是否重复的问题，如果有多个同名的编译环境，配置项目编译环境的时候无法选择

**Comment by colynn** [comment]
@stainzhu  would you want to work on that ?
