### ISSUE TITLE
应用部署失败，数据错乱

### ISSUE THREAD

**Issue by sampsonye** [go-atomci/atomci#177]
### 运行环境
* `应用版本`:
     * `atomci-frontend`: 1.5.1
     * `atomci`:1.5.1
* `Kubernetes`:1.24

### 截图
![6b13639fb4a7fcf0b4c6214ae0cd2e8](https://user-images.githubusercontent.com/5895634/189247925-14c69da2-0a29-4b1b-8cff-50cd0800880c.jpg)

**Comment by colynn** [comment]
对于部署pipeline 是project_id +  stage_id来组成的， 未包含project_app_id的元素，重复触发时是基于update 对应的pipeline来处理的
