### ISSUE TITLE
使用atomci自带的kaniko构建多阶段的docker镜像时很慢（3-5倍以上）

### ISSUE THREAD

**Issue by sampsonye** [go-atomci/atomci#180]
### 运行环境
* `应用版本`:
     * `atomci-frontend`: 1.5.1
     * `atomci`:1.5.1
* `Kubernetes`:1.24

### 截图
![419f6d75dd731b1dc26cd8e13ef7a2a](https://user-images.githubusercontent.com/5895634/189279303-14d068d4-fd6d-43fe-9253-4d876aff4574.jpg)

https://github.com/GoogleContainerTools/kaniko/pull/1735
建议kaniko升级

**Comment by colynn** [comment]
I already try to upgrade to [`v1.9.0`](colynn/kaniko-executor:v1.6.0-debug)   and origin tag archived as `colynn/kaniko-executor:v1.6.0-debug`

**Comment by sampsonye** [comment]
使用最新的kaniko后，性能并未得到提升，需要考虑更多方案
![9ed8a220a70c6b23a3337c47f82bf16](https://user-images.githubusercontent.com/5895634/190114805-f80bcd8a-edca-4935-9620-e98e4a07729a.jpg)

> Tips:
*相同配置下使用Docker Build --no-cache 构建通常在2分钟以内完成*

**Comment by sampsonye** [comment]
经排查，该问题主要是kaniko对dockerignore的支持/多阶段构建性能差有关。建议：
1. dockerignore书写时尽量详细
2. 尽量避免多阶段构建（20220915目前）/ COPY 严格控制

https://github.com/GoogleContainerTools/kaniko/issues/2248
