### ISSUE TITLE
docker-compose 部署后， 页面无法打开，访问一直请求 getCurrentUser接口

### ISSUE THREAD

**Issue by colynn** [go-atomci/atomci#2]
* `应用版本`:
     * `atomci-frontend`:  latest
     * `atomci`: latest
* `Kubernetes`: v1.18.3

## 问题描述
docker-compose 部署后， 访问一直请求  getCurrentUser接口

## 解决方案

```sh
# 重启atomci服务后，就可正常访问了。
$ docker-compose restart atomci
```

**Comment by sampsonye** [comment]
经分析，本质原因是默认数据库中用户没有关联角色导致
![image](https://user-images.githubusercontent.com/5895634/145354225-b2364e09-5f9b-40b0-9349-b209965cced0.png)
![image](https://user-images.githubusercontent.com/5895634/145354344-8a4306c7-dea5-46c2-88b0-f6e390d5b7e9.png)

**Comment by colynn** [comment]
对的，1.2.1版本重启就会重新初始化角色，就可解决这个问题，目前正在[调整初始化逻辑](https://github.com/go-atomci/atomci/tree/feature-user-permission)，统一依赖于运行时，不再依赖`cli`

**Comment by sampsonye** [comment]
建议可以手动添加相关数据 sql脚本：
```
insert into sys_group_role(`group`,`role`,`description`) values('system','admin','系统管理员');
insert into sys_group_role_user(`group`,`user`,`role`) values('system','admin','admin');
```

**Comment by colynn** [comment]
> 建议可以手动添加相关数据 sql脚本：
> 
> ```
> insert into sys_group_role(`group`,`role`,`description`) values('system','admin','系统管理员');
> insert into sys_group_role_user(`group`,`user`,`role`) values('system','admin','admin');
> ```

可以添加角色，只是添加了角色，该角色的操作还是空，且操作依赖于资源的注册，现在还是统一了初始化的方式：
先初始化资源、操作，然后再初始化用户、角色。

[initialize/init.go](https://github.com/go-atomci/atomci/blob/feature-user-permission/initialize/init.go)  这里已经调整，目前是pre-release阶段

**Comment by colynn** [comment]
#9 修复后的版本　[1.3.0](https://github.com/go-atomci/atomci/releases/tag/v1.3.0)已经release，　isssue closed.
