### ISSUE TITLE
相同deployment不能在不同命名空间部署

### ISSUE THREAD

**Issue by sampsonye** [go-atomci/atomci#23]
### 运行环境
* `应用版本`:
     * `atomci-frontend`: latest
     * `atomci`:latest
* `Kubernetes`: k3s v1.21.0

### 问题描述
相同deployment不能在不同命名空间部署
```
deploy application occur error: Error: 500, InternalServerError, internal server error, quant-first-blood-3-deployment:the application(quant-first-blood-3-deployment) is existed in namespace [blood] of cluster Tencent-K8S, and you have no right to cover the old application, cluster: Tencent-K8S, namespace: test-blood
```

### 截图
![image](https://user-images.githubusercontent.com/5895634/147041766-1324e72e-a5c4-4547-beb9-929d65208c3f.png)

**Comment by colynn** [comment]
fixed
