### ISSUE TITLE
删除k8s的集成 配置后，conf/k8sconfig 对应的k8s配置未做删除相关处理

### ISSUE THREAD

**Issue by colynn** [go-atomci/atomci#35]
### 运行环境
* `应用版本`:
     * `atomci-frontend`:  1.3.0
     * `atomci`: 1.3.0
* `Kubernetes`: null

### 问题描述
如题，『服务集成』删除k8s类型的配置后， 对应的 `conf/k8sconfig`下k8s文件并未做删除等处理

### 截图
无

『服务集成』 -- 列表 -- 点击『删除』操作 即可复现

**Comment by sampsonye** [comment]
PR-#107 将K8S相关配置迁移到了数据库，本问题随之解决
