### ISSUE TITLE
[Support]尝试配置Kubernetes，请问Kubernetes Config是哪个文件？

### ISSUE THREAD

**Issue by sampsonye** [go-atomci/atomci#5]
尝试配置Kubernetes，请问Kubernetes Config是哪个文件？
k8s :v1.23.1

另技术沟通的二维码无法加入
![lADPJxDjvycAug7NCWDNBJg_1176_2400](https://user-images.githubusercontent.com/5895634/145511621-c41bc923-181f-4f2e-a34a-336e04cb5434.jpg)

**Comment by sampsonye** [comment]
Kubernetes Config : ~/.kube/config

**Comment by colynn** [comment]
使用 /etc/kubernetes/admin.conf  ，也就是 ~/.kuber/config，有＂测试连接＂的功能　可以验证下信息有效性

**Comment by colynn** [comment]
> 尝试配置Kubernetes，请问Kubernetes Config是哪个文件？ k8s :v1.23.1
> 
> 另技术沟通的二维码无法加入 !

可以添加微信: __colynnliu__ , 邀请入群
