### ISSUE TITLE
项目升级时如何同步配置变更？- 引入 migrate 工具

### ISSUE THREAD

**Issue by sampsonye** [go-atomci/atomci#55]
### 运行环境
* `应用版本`:
     * `atomci-frontend`: latest
     * `atomci`: latest
* `Kubernetes`: v1.23.1

### 问题描述
latest新增了通知功能，更新后发现本地的app.config中并没有自动生成对应的配置
如何“人性化”地在升级过程中将新的配置告知使用者呢？

**Comment by colynn** [comment]
目前阶段，手工更新docker-compose的tar的配置还是少不了，会重新打包下 latest版本的 docker-compose 包，将配置包含进去

**Comment by colynn** [comment]
1. 新增 app.config.template 的示例配置文件；
2.调研引入 migrate 工具，比如 https://github.com/golang-migrate/migrate
