### ISSUE TITLE
是否考虑支持将 阿里云容器服务作为镜像仓库？

### ISSUE THREAD

**Issue by sampsonye** [go-atomci/atomci#6]
**您有什么需求，是否与某个功能或问题相关? 请描述**
目前我们镜像统一托管在阿里云的镜像仓库中，具备很好的性能以及扩展性

**你想要的解决方案是什么**
在除支持harbor之外，还能支持阿里云（腾讯云？）等流行平台的镜像仓库

**Comment by colynn** [comment]
对于镜像仓库的类型 依赖其实很弱，只有『服务集成』里 『测试连接』需要根据具体的镜像仓库类型来验证；

在cicd的流水线中只是获取/添加 镜像仓库的验证信息，所以只要网络是通的，逻辑上就可以支持，只是『测试连接』的功能暂时不可用，要自己保证验证信息的有效性。

**Comment by colynn** [comment]
from @sampsonye  

sys_integrate_setting /  `type`字段的: `habor` 调整为`registry`， 不特定harbor, 可以用docker的client来验证账号密码的正确性 
剩下的推送交给kaniko
