### ISSUE TITLE
conf缺少k8s配置

### ISSUE THREAD

**Issue by liuzilong66666** [go-atomci/atomci#84]
### 运行环境
* `应用版本`:
     * `atomci-frontend`: 
     * `atomci`:
* `Kubernetes`:

### 问题描述
conf缺少k8s配置
### 截图

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/49033484/154665447-bfa99f0a-5922-4418-b70f-bbcb2562be92.png">

**Comment by fanhousanbu** [comment]
是否之前配置过？如果之前配置过，需要重新配置再保存

> 可能是由 #61 引起的break change

**Comment by liuzilong66666** [comment]
看起来像是conf目录下缺少了k8sconfig目录，上一个版本中是有这个目录的

**Comment by colynn** [comment]
> k8sconfig



> 

“服务集成” 那里重新配置下，`k8sconfig`的目录会自动创建出来
